blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Chat
    url: https://github.com/NickTheDevOpsGuy/Snake/discussions/3
    about: Use GitHub Discussions for general questions, ideas, or community talk.
